# Generated by Django 6.0 on 2025-12-15 08:12

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('GM', 'المدير العام'), ('M', 'مدير'), ('E', 'موظف')], default='GM', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='اسم الخطة الاستراتيجية', max_length=200, unique=True)),
                ('vision', models.TextField(help_text='الرؤية')),
                ('mission', models.TextField(help_text='الرسالة')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, help_text='تاريخ بداية الخطة', null=True)),
                ('end_date', models.DateField(blank=True, help_text='تاريخ نهاية الخطة', null=True)),
                ('plan_status', models.CharField(choices=[('T', 'نشطة'), ('F', 'غير نشطة')], default='T', help_text='حالة الخطة', max_length=1)),
            ],
            options={
                'verbose_name': 'StrategicPlan',
                'verbose_name_plural': 'StrategicPlans',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPMS_app.initiative')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(help_text='عنوان الهدف الاستراتيجي', max_length=200)),
                ('description', models.TextField(help_text='وصف الهدف الاستراتيجي')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, help_text='تاريخ بداية الهدف', null=True)),
                ('end_date', models.DateField(blank=True, help_text='تاريخ نهاية الهدف', null=True)),
                ('goal_status', models.CharField(choices=[('NS', 'لم يبدأ بعد'), ('IP', 'قيد التنفيذ'), ('D', 'متأخر'), ('C', 'مكتمل')], default='NS', help_text='حالة الهدف', max_length=2)),
                ('goal_priority', models.CharField(choices=[('C', 'حرجة'), ('H', 'عالية'), ('M', 'متوسطة'), ('L', 'منخفضة')], default='C', help_text='أهمية الهدف', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='CPMS_app.department')),
                ('strategicplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='CPMS_app.strategicplan')),
            ],
            options={
                'verbose_name': 'StrategicGoal',
                'verbose_name_plural': 'StrategicGoals',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='initiative',
            name='strategic_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPMS_app.strategicgoal'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPMS_app.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPMS_app.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('progress', models.DecimalField(decimal_places=0, max_digits=10)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPMS_app.initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='محتوى الملاحظة')),
                ('note_status', models.CharField(choices=[('R', 'مقروءة'), ('U', 'غير مقروءة')], default='R', help_text='حالة الملاحظة', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='CPMS_app.department')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='CPMS_app.initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, null=True)),
                ('record_id', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['id'],
            },
        ),
    ]
